package com.etc.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminid
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.adminname
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.password
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminid
     *
     * @return the value of t_admin.adminid
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminid
     *
     * @param adminid the value for t_admin.adminid
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.adminname
     *
     * @return the value of t_admin.adminname
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.adminname
     *
     * @param adminname the value for t_admin.adminname
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.password
     *
     * @return the value of t_admin.password
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.password
     *
     * @param password the value for t_admin.password
     *
     * @mbg.generated Thu Sep 27 13:43:21 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}