package com.etc.entity;

import java.util.Date;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.fid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    private Long fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.tid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.pid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend.fdate
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    private Date fdate;


    private Parents parent;

    public Parents getParents() {
        return parent;
    }

    public void setParents(Parents parents) {
        this.parent = parents;
    }

    private Integer count;

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.fid
     *
     * @return the value of t_friend.fid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.fid
     *
     * @param fid the value for t_friend.fid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.tid
     *
     * @return the value of t_friend.tid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.tid
     *
     * @param tid the value for t_friend.tid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.pid
     *
     * @return the value of t_friend.pid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.pid
     *
     * @param pid the value for t_friend.pid
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend.fdate
     *
     * @return the value of t_friend.fdate
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public Date getFdate() {
        return fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend.fdate
     *
     * @param fdate the value for t_friend.fdate
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }

    public Friend() {
    }

    public Friend(Long fid, Integer tid, Integer pid, Date fdate) {
        this.fid = fid;
        this.tid = tid;
        this.pid = pid;
        this.fdate = fdate;
    }

    public Friend(Integer tid, Integer pid) {
        this.tid = tid;
        this.pid = pid;
    }

    @Override
    public String toString() {
        return "Friend{" +
                "fid=" + fid +
                ", tid=" + tid +
                ", pid=" + pid +
                ", fdate=" + fdate +
                ", parent=" + parent +
                ", count=" + count +
                '}';
    }
}