package com.etc.entity;

import java.util.Arrays;

public class Parents {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.parentid
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.parentname
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private String parentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.password
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.lon
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private String lon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.lat
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.clicktime
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private Long clicktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.studentname
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private String studentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_parents.images
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    private byte[] images;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.parentid
     *
     * @return the value of t_parents.parentid
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.parentid
     *
     * @param parentid the value for t_parents.parentid
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.parentname
     *
     * @return the value of t_parents.parentname
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public String getParentname() {
        return parentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.parentname
     *
     * @param parentname the value for t_parents.parentname
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setParentname(String parentname) {
        this.parentname = parentname == null ? null : parentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.password
     *
     * @return the value of t_parents.password
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.password
     *
     * @param password the value for t_parents.password
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.lon
     *
     * @return the value of t_parents.lon
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.lon
     *
     * @param lon the value for t_parents.lon
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.lat
     *
     * @return the value of t_parents.lat
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.lat
     *
     * @param lat the value for t_parents.lat
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.clicktime
     *
     * @return the value of t_parents.clicktime
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public Long getClicktime() {
        return clicktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.clicktime
     *
     * @param clicktime the value for t_parents.clicktime
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setClicktime(Long clicktime) {
        this.clicktime = clicktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.studentname
     *
     * @return the value of t_parents.studentname
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.studentname
     *
     * @param studentname the value for t_parents.studentname
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_parents.images
     *
     * @return the value of t_parents.images
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public byte[] getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_parents.images
     *
     * @param images the value for t_parents.images
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    public void setImages(byte[] images) {
        this.images = images;
    }

    public Parents() {
    }

    public Parents(Integer parentid, String parentname, String password, String lon, String lat, Long clicktime, String studentname, byte[] images) {
        this.parentid = parentid;
        this.parentname = parentname;
        this.password = password;
        this.lon = lon;
        this.lat = lat;
        this.clicktime = clicktime;
        this.studentname = studentname;
        this.images = images;
    }

    public Parents(Integer parentid) {
        this.parentid = parentid;
    }

    public Parents(Integer parentid, String parentname, String password, String lon, String lat, Long clicktime, byte[] images) {
        this.parentid = parentid;
        this.parentname = parentname;
        this.password = password;
        this.lon = lon;
        this.lat = lat;
        this.clicktime = clicktime;
        this.images = images;
    }

    public Parents(String parentname, String password, String lon, String lat, Long clicktime, byte[] images) {
        this.parentname = parentname;
        this.password = password;
        this.lon = lon;
        this.lat = lat;
        this.clicktime = clicktime;
        this.images = images;
    }

    public Parents(String parentname, String password) {
        this.parentname = parentname;
        this.password = password;
    }

    public Parents(Integer parentid, String parentname, String password, String lon, String lat, byte[] images) {
        this.parentid = parentid;
        this.parentname = parentname;
        this.password = password;
        this.lon = lon;
        this.lat = lat;
        this.images = images;
    }

    public Parents(String parentname, String password, String lon, String lat, byte[] images) {
        this.parentname = parentname;
        this.password = password;
        this.lon = lon;
        this.lat = lat;
        this.images = images;
    }

    public Parents(Long clicktime) {
        this.clicktime = clicktime;
    }

    public Parents(String studentname) {
        this.studentname = studentname;
    }

    @Override
    public String toString() {
        return "Parents{" +
                "parentid=" + parentid +
                ", parentname='" + parentname + '\'' +
                ", password='" + password + '\'' +
                ", lon='" + lon + '\'' +
                ", lat='" + lat + '\'' +
                ", clicktime=" + clicktime +
                ", studentname='" + studentname + '\'' +
                ", images=" + Arrays.toString(images) +
                '}';
    }
}