package com.etc.entity;

public class Students {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.studentid
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.studentname
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String studentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.gender
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.grade
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.course
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.phone
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.address
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.teaid
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private Integer teaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.state
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_students.teaname
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    private String teaname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.studentid
     *
     * @return the value of t_students.studentid
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.studentid
     *
     * @param studentid the value for t_students.studentid
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.studentname
     *
     * @return the value of t_students.studentname
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.studentname
     *
     * @param studentname the value for t_students.studentname
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.gender
     *
     * @return the value of t_students.gender
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.gender
     *
     * @param gender the value for t_students.gender
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.grade
     *
     * @return the value of t_students.grade
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.grade
     *
     * @param grade the value for t_students.grade
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.course
     *
     * @return the value of t_students.course
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.course
     *
     * @param course the value for t_students.course
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.phone
     *
     * @return the value of t_students.phone
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.phone
     *
     * @param phone the value for t_students.phone
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.address
     *
     * @return the value of t_students.address
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.address
     *
     * @param address the value for t_students.address
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.teaid
     *
     * @return the value of t_students.teaid
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.teaid
     *
     * @param teaid the value for t_students.teaid
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.state
     *
     * @return the value of t_students.state
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.state
     *
     * @param state the value for t_students.state
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_students.teaname
     *
     * @return the value of t_students.teaname
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public String getTeaname() {
        return teaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_students.teaname
     *
     * @param teaname the value for t_students.teaname
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    public void setTeaname(String teaname) {
        this.teaname = teaname == null ? null : teaname.trim();
    }

    @Override
    public String toString() {
        return "Students{" +
                "studentid=" + studentid +
                ", studentname='" + studentname + '\'' +
                ", gender='" + gender + '\'' +
                ", grade='" + grade + '\'' +
                ", course='" + course + '\'' +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                ", teaid=" + teaid +
                ", state='" + state + '\'' +
                ", teaname='" + teaname + '\'' +
                '}';
    }
}