package com.etc.entity;

import java.util.Arrays;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teaid
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private Integer teaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teaname
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String teaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.gender
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.password
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.school
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.score
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.phone
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String phone;

    /////////////////////////////////////
    private String course;
    private String grade;

    public String getCourse() {
        return course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

    public String getGrade() {
        return grade;
    }

    public void setGrade(String grade) {
        this.grade = grade;
    }
    ////////////////////////////////////////////////////////////////

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.address
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.description
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.experience
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.freetime
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String freetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.lon
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String lon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.lat
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.stucount
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private Integer stucount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.images
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private Object images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.payimage
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    private byte[] payimage;


    private Courseinfo courseinfos;
    public Courseinfo getCourseinfos() {
        return courseinfos;
    }
    public void setCourseinfos(Courseinfo courseinfos) {
        this.courseinfos = courseinfos;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teaid
     *
     * @return the value of t_teacher.teaid
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public Integer getTeaid() {
        return teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teaid
     *
     * @param teaid the value for t_teacher.teaid
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setTeaid(Integer teaid) {
        this.teaid = teaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teaname
     *
     * @return the value of t_teacher.teaname
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getTeaname() {
        return teaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teaname
     *
     * @param teaname the value for t_teacher.teaname
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setTeaname(String teaname) {
        this.teaname = teaname == null ? null : teaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.gender
     *
     * @return the value of t_teacher.gender
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.gender
     *
     * @param gender the value for t_teacher.gender
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.password
     *
     * @return the value of t_teacher.password
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.password
     *
     * @param password the value for t_teacher.password
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.school
     *
     * @return the value of t_teacher.school
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.school
     *
     * @param school the value for t_teacher.school
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.score
     *
     * @return the value of t_teacher.score
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.score
     *
     * @param score the value for t_teacher.score
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.phone
     *
     * @return the value of t_teacher.phone
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.phone
     *
     * @param phone the value for t_teacher.phone
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.address
     *
     * @return the value of t_teacher.address
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.address
     *
     * @param address the value for t_teacher.address
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.description
     *
     * @return the value of t_teacher.description
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.description
     *
     * @param description the value for t_teacher.description
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.experience
     *
     * @return the value of t_teacher.experience
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.experience
     *
     * @param experience the value for t_teacher.experience
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setExperience(String experience) {
        this.experience = experience == null ? null : experience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.freetime
     *
     * @return the value of t_teacher.freetime
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getFreetime() {
        return freetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.freetime
     *
     * @param freetime the value for t_teacher.freetime
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setFreetime(String freetime) {
        this.freetime = freetime == null ? null : freetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.lon
     *
     * @return the value of t_teacher.lon
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.lon
     *
     * @param lon the value for t_teacher.lon
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.lat
     *
     * @return the value of t_teacher.lat
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.lat
     *
     * @param lat the value for t_teacher.lat
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.stucount
     *
     * @return the value of t_teacher.stucount
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public Integer getStucount() {
        return stucount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.stucount
     *
     * @param stucount the value for t_teacher.stucount
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setStucount(Integer stucount) {
        this.stucount = stucount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.images
     *
     * @return the value of t_teacher.images
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public Object getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.images
     *
     * @param images the value for t_teacher.images
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setImages(Object images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.payimage
     *
     * @return the value of t_teacher.payimage
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public byte[] getPayimage() {
        return payimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.payimage
     *
     * @param payimage the value for t_teacher.payimage
     *
     * @mbg.generated Mon Sep 17 14:15:17 CST 2018
     */
    public void setPayimage(byte[] payimage) {
        this.payimage = payimage;
    }

    public Teacher() {
    }

    public Teacher(Integer teaid, String teaname, String gender, String password,
                   String school, String score, String phone, String address, String description,
                   String experience, String freetime, String lon, String lat, Integer stucount, Object images, byte[] payimage) {
        this.teaid = teaid;
        this.teaname = teaname;
        this.gender = gender;
        this.password = password;
        this.school = school;
        this.score = score;
        this.phone = phone;
        this.address = address;
        this.description = description;
        this.experience = experience;
        this.freetime = freetime;
        this.lon = lon;
        this.lat = lat;
        this.stucount = stucount;
        this.images = images;
        this.payimage = payimage;
    }

    public Teacher(String teaname, String gender, String password, String school, String score,
                   String phone, String address, String description, String experience, String freetime,
                   String lon, String lat, Integer stucount, Object images, byte[] payimage) {
        this.teaname = teaname;
        this.gender = gender;
        this.password = password;
        this.school = school;
        this.score = score;
        this.phone = phone;
        this.address = address;
        this.description = description;
        this.experience = experience;
        this.freetime = freetime;
        this.lon = lon;
        this.lat = lat;
        this.stucount = stucount;
        this.images = images;
        this.payimage = payimage;
    }

    public Teacher(String teaname, String password) {
        this.teaname = teaname;
        this.password = password;
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "teaid=" + teaid +
                ", teaname='" + teaname + '\'' +
                ", gender='" + gender + '\'' +
                ", password='" + password + '\'' +
                ", school='" + school + '\'' +
                ", score='" + score + '\'' +
                ", phone='" + phone + '\'' +
                ", address='" + address + '\'' +
                ", description='" + description + '\'' +
                ", experience='" + experience + '\'' +
                ", freetime='" + freetime + '\'' +
                ", lon='" + lon + '\'' +
                ", lat='" + lat + '\'' +
                ", stucount=" + stucount +
                ", images=" + images +
                ", payimage=" + Arrays.toString(payimage) +
                ", courseinfos=" + courseinfos +
                '}';
    }
}