package com.etc.dao;

import com.etc.entity.Chatinfo;
import com.etc.entity.ChatinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ChatinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    long countByExample(ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int deleteByExample(ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int deleteByPrimaryKey(Integer chatid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int insert(Chatinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int insertSelective(Chatinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    List<Chatinfo> selectByExampleWithBLOBs(ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    List<Chatinfo> selectByExample(ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    Chatinfo selectByPrimaryKey(Integer chatid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") Chatinfo record, @Param("example") ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Chatinfo record, @Param("example") ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int updateByExample(@Param("record") Chatinfo record, @Param("example") ChatinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int updateByPrimaryKeySelective(Chatinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Chatinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chatinfo
     *
     * @mbg.generated Mon Sep 17 14:15:18 CST 2018
     */
    int updateByPrimaryKey(Chatinfo record);

    List<Chatinfo> descSelect(@Param("receiveid")Integer receiveid,@Param("sendid") Integer sendid,@Param("receiveid")Integer receive,@Param("sendid")Integer send);

}