package com.etc.dao;

import com.etc.entity.Courses;
import com.etc.entity.CoursesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface CoursesDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    long countByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int deleteByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int deleteByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int insert(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int insertSelective(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    List<Courses> selectByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    Courses selectByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") Courses record, @Param("example") CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int updateByExample(@Param("record") Courses record, @Param("example") CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int updateByPrimaryKeySelective(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courses
     *
     * @mbg.generated Sat Oct 06 09:52:23 CST 2018
     */
    int updateByPrimaryKey(Courses record);

    //通过家长姓名查询该家长的课程
    List<Courses> selectbyparentname(String parentname);

    List<Courses> selectcoursebyteaname(String teaname);
}