package com.etc.dao;

import com.etc.entity.Courseinfo;
import com.etc.entity.CourseinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface CourseinfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    long countByExample(CourseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int deleteByExample(CourseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int deleteByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int insert(Courseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int insertSelective(Courseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    List<Courseinfo> selectByExample(CourseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    Courseinfo selectByPrimaryKey(Integer courseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") Courseinfo record, @Param("example") CourseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int updateByExample(@Param("record") Courseinfo record, @Param("example") CourseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int updateByPrimaryKeySelective(Courseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courseinfo
     *
     * @mbg.generated Thu Sep 20 13:58:20 CST 2018
     */
    int updateByPrimaryKey(Courseinfo record);

    int updateByteaname(Courseinfo record);

    List<Courseinfo> selectBycourse(String course);
}