package com.etc.dao;

import com.etc.entity.Friend;
import com.etc.entity.FriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    long countByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int deleteByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int deleteByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int insertSelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    List<Friend> selectByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    Friend selectByPrimaryKey(Long fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int updateByExample(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int updateByPrimaryKeySelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_friend
     *
     * @mbg.generated Sat Sep 29 09:42:24 CST 2018
     */
    int updateByPrimaryKey(Friend record);
}