package com.etc.dao;

import com.etc.entity.Parents;
import com.etc.entity.ParentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface ParentsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    long countByExample(ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int deleteByExample(ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int deleteByPrimaryKey(Integer parentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int insert(Parents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int insertSelective(Parents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    List<Parents> selectByExampleWithBLOBs(ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    List<Parents> selectByExample(ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    Parents selectByPrimaryKey(Integer parentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") Parents record, @Param("example") ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Parents record, @Param("example") ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int updateByExample(@Param("record") Parents record, @Param("example") ParentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int updateByPrimaryKeySelective(Parents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Parents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_parents
     *
     * @mbg.generated Wed Oct 03 17:25:54 CST 2018
     */
    int updateByPrimaryKey(Parents record);
}