package com.etc.dao;

import com.etc.entity.Students;
import com.etc.entity.StudentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface StudentsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    long countByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int deleteByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int deleteByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int insertSelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    List<Students> selectByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    Students selectByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") Students record, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int updateByExample(@Param("record") Students record, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int updateByPrimaryKeySelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_students
     *
     * @mbg.generated Fri Sep 28 17:33:21 CST 2018
     */
    int updateByPrimaryKey(Students record);

    int updateOrderState(String studentname);

    List<Students> selectorderbyteaid(String teaname);

    int deleteorder(String studentname);
    int selectgendercount(String grade,String gender);
}